language: haskell

env:
  - GHCVER=7.6.3
  - GHCVER=7.8.4
  - GHCVER=7.10.1

before_install:
  - sudo add-apt-repository -y ppa:hvr/ghc
  - sudo apt-get update
  - sudo apt-get install ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH
  - sudo apt-get install cabal-install-1.22
  - export PATH=/opt/cabal/1.22/bin:$PATH
  - ghc --version
  - cabal --version
  - cabal install gtk2hs-buildtools

script:
  - cabal configure --enable-tests --ghc-options=-Werror && cabal build && cabal test
  - cabal install --ghc-options=-Werror
